name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm test

  pre-prod-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Pre-Prod
        run: echo "Running the pre-production deployment stage."

  prod-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Prod
        run: echo "Running the production deployment stage."